### PR TITLE
Comenv.f for hyperbolic orbits

### PR DESCRIPTION
**Pull request by GiacobboNicola**

### CODE REVIEW

**Comment by GiacobboNicola** [comment]
@lwang-astro, did you remove the petar.mobse executable? I wanted to use it to make some tests.

**Comment by GiacobboNicola** [comment]
@lwang-astro, I wanted to do some tests, but I've notice petar.mobse is no longer available.

**Comment by lwang-astro** [comment]
It should be available. I have no problem to compile petar.mobse and install it. Have you changed Makefile or use the offical ones?

**Comment by GiacobboNicola** [comment]
Hi @lwang-astro, sorry for the late reply but I haven't received the notification. Anyway, I used the official Makefile.

**Comment by lwang-astro** [comment]
Have you re configure the code and make install?

Windows 10 版のメ`ル<https://go.microsoft.com/fwlink/?LinkId=550986>から送信

差出人: GNicola<mailto:notifications@github.com>
送信日r: 2021年2月24日 19:45
宛先: lwang-astro/PeTar<mailto:PeTar@noreply.github.com>
CC: lwang-astro<mailto:longwang.astro@live.com>; Mention<mailto:mention@noreply.github.com>
件名: Re: [lwang-astro/PeTar] Comenv.f for hyperbolic orbits (#12)


Hi @lwang-astro<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flwang-astro&data=04%7C01%7C%7C81cfc42e5a10495e305e08d8d8b15155%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637497603369766035%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=uS0gWKbaLZA%2FQjfGzCH%2FO5g0iQu1P4A6mPZ5LFvfizo%3D&reserved=0>, sorry for the late reply but I haven't received the notification. Anyway, I used the official Makefile.

―

**Comment by GiacobboNicola** [comment]
I did. I'll try again and let you know what's the result.

**Pull request merged**
